AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

# Long blocks are already caught by the method length cop, this only causes an
# offense for configuration blocks where its fine for the block to be very long
Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
